# Generated by Django 2.1.1 on 2020-01-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCampaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('vote_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_backend.VoteCampaign')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voteoption',
            unique_together={('vote_campaign', 'option')},
        ),
    ]
