# Generated by Django 2.1.1 on 2020-01-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_backend.VoteCampaign')),
            ],
        ),
        migrations.RenameField(
            model_name='voteoption',
            old_name='vote_campaign',
            new_name='campaign',
        ),
        migrations.AlterUniqueTogether(
            name='voteoption',
            unique_together={('campaign', 'option')},
        ),
        migrations.AddField(
            model_name='voterecord',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_backend.VoteOption'),
        ),
        migrations.AlterUniqueTogether(
            name='voterecord',
            unique_together={('user_id', 'campaign')},
        ),
    ]
