# Generated by Django 2.1.1 on 2020-02-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_backend', '0006_voterecord_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterecord',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
